#!/usr/bin/env bash
: "${VERBOSITY:=0}"
: "${FETCHR_CACHE:=/tmp}"
. src/util.bash
test_env

main () {
  src/vigil.sh

  fetch_wrapper 'supabase-kubernetes' 'https://github.com/supabase-community/supabase-kubernetes.git'
  fetch_wrapper 'FOSSBilling-charts' 'https://github.com/joshuacox/FOSSBilling-charts.git'
  fetch_wrapper 'helm-drupal' 'https://github.com/drupalwxt/helm-drupal.git'
  fetch_wrapper 'garage' 'https://git.deuxfleurs.fr/Deuxfleurs/garage'
  fetch_wrapper 'cvat' 'https://github.com/cvat-ai/cvat'
  cd ${FETCHR_CACHE}/cvat
  cp -av helm-chart ${URBAN_DISCO_BASE_PATH}/charts/cvat
  rm ${URBAN_DISCO_BASE_PATH}/charts/cvat/analytics
  cp -av components/analytics ${URBAN_DISCO_BASE_PATH}/charts/cvat/
  cd ${FETCHR_CACHE}/helm-drupal/charts
  git pull
  cp -av solr    ${URBAN_DISCO_BASE_PATH}/charts/
  cp -av drupal  ${URBAN_DISCO_BASE_PATH}/charts/
  cp -av varnish ${URBAN_DISCO_BASE_PATH}/charts/
  cd ${FETCHR_CACHE}/supabase-kubernetes
  git pull
  cd ${FETCHR_CACHE}/supabase-kubernetes/charts
  cp -av supabase ${URBAN_DISCO_BASE_PATH}/charts/
  cd ${FETCHR_CACHE}/FOSSBilling-charts
  git pull
  cp -av ${FETCHR_CACHE}/FOSSBilling-charts ${URBAN_DISCO_BASE_PATH}/charts/FOSSBilling
  rm -Rf ${URBAN_DISCO_BASE_PATH}/charts/FOSSBilling/.git
  cd ${FETCHR_CACHE}/garage
  git pull
  cp -av ${FETCHR_CACHE}/garage/script/helm/garage ${URBAN_DISCO_BASE_PATH}/charts/

  cd ${URBAN_DISCO_BASE_PATH}
  cd ${URBAN_DISCO_BASE_PATH}/charts
  git checkout nextjs-docker
  git checkout sass-starter
  git checkout urban-mosquitto
  mkdir minio
  cd minio
  helm fetch --untar minio-operator/operator
  helm fetch --untar minio-operator/tenant
  cd ${URBAN_DISCO_BASE_PATH}/charts
  helm fetch --untar openebs-monitoring/monitoring
  mv -v monitoring openebs-monitoring
  helm fetch --untar haproxytech/kubernetes-ingress
  mv -v kubernetes-ingress haproxy-ingress
  helm pull --untar oci://ghcr.io/spegel-org/helm-charts/spegel
}

time main $@
