#!/usr/bin/env bash
: "${VERBOSITY:=0}"
: "${FETCHR_CACHE:=/tmp}"
. src/util.bash
test_env

main () {
  set -eux

  bash -ux repo_list
  helm repo update

  rm -Rf charts
  mkdir charts

  ./custom

  cd ${URBAN_DISCO_BASE_PATH}/charts
  bash -eux ../list_fetch
}

time main $@
