#!/usr/bin/env bash
: ${VERBOSITY:=0}
: ${FETCHR_CACHE:=/tmp}


main () {
  URBAN_DISCO_BASE_PATH=$(pwd)

  for i in $(cat repo_list); do
    echo "helm repo add $i"
  done
  for i in $(cat repo_list); do
    echo "helm fetch --untarl $i"
  done
}

time main $@
