annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: "Initial release of v4 chart."
apiVersion: v2
appVersion: 3.7.0
description: Kubernetes operator for Fluent Bit and Fluentd—define collectors, pipelines,
  and outputs as custom resources.
home: https://github.com/fluent/fluent-operator
icon: https://raw.githubusercontent.com/fluent/fluent-operator/master/docs/images/fluent-operator-icon.svg
keywords:
- logging
- fluent-bit
- fluentd
- operator
maintainers:
- email: dehaocheng@kubesphere.io
  name: wenchajun
- email: marco.franssen@gmail.com
  name: marcofranssen
  url: https://marcofranssen.nl
- email: joshbaird@gmail.com
  name: joshuabaird
name: fluent-operator
sources:
- https://github.com/fluent/fluent-operator
version: 4.0.0
