annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: |
        chore: update OpenBao to 2.5.2
      links:
        - name: OpenBao 2.5.2 Release
          url: https://github.com/openbao/openbao/releases/tag/v2.5.2
  artifacthub.io/containsSecurityUpdates: "true"
  charts.openshift.io/name: Openbao
apiVersion: v2
appVersion: v2.5.2
description: Official OpenBao Chart
home: https://github.com/openbao/openbao-helm
icon: https://raw.githubusercontent.com/openbao/artwork/refs/heads/main/color/openbao-color.svg
keywords:
- vault
- openbao
- security
- encryption
- secrets
- management
- automation
- infrastructure
kubeVersion: '>= 1.30.0-0'
maintainers:
- email: openbao-security@lists.openssf.org
  name: OpenBao
  url: https://openbao.org
name: openbao
sources:
- https://github.com/openbao/openbao-helm
version: 0.26.2
